(load("contrib_ode"),0);
0$

/* ODE tests - Second order linear equations 401-423

  Reference:
    E Kamke, Differentialgleichungen Losungsmethoden und Losungen, 
    Vol 1, Geest & Portig, Leipzig, 1961
*/

/* Print ode number*/
(pn_(n_):=print("Kamke ODE 2.",n_),true);
true;


check_result(eqn, ans) := block(
    [],
    if length(ans)>0 then
        (
        ode_check(eqn,ans[1])
        )
    )$

testmode: true;

/* Kamke 2. 401  */ 
assume(b>0,4*b>a^2);
(pn_(401),ans:ode2singular(eqn:'diff(y,x,2)=-(3*x^2+a)*'diff(y,x,1)/x^3-b*y/x^6,y,x));
check_result(eqn, ans);
forget(b>0,4*b>a^2);

/* Kamke 2. 402  */
(pn_(402),ans:ode2singular(eqn:'diff(y,x,2)=-((1-4*a)*x^2-1)*'diff(y,x,1)/(x*(x^2-1))-(4*a*(a+1)*x^4+(x^2-1)^2*(x^2-v^2)-2*a*x^2*(x^2-1))*y/(x^2*(x^2-1)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 403  */ 
(pn_(403),ans:ode2singular(eqn:'diff(y,x,2)=(-(-b2-a2+1)/(x-c_2)-(-b1-a1+1)/(x-c_1)-(-b3-a3+1)/(x-c3))*'diff(y,x,1)-(a2*b2*(c_2-c3)*(c_2-c_1)/(x-c_2)+a1*b1*(c_1-c3)*(c_1-c_2)/(x-c_1)+a3*b3*(c3-c_1)*(c3-c_2)/(x-c3))*y/((x-c3)*(x-c_1)*(x-c_2)),y,x));
check_result(eqn, ans);

/* Kamke 2. 404  */
(pn_(404),ans:ode2singular(eqn:'diff(y,x,2)=(-2*x^2-1)*'diff(y,x,1)/x^3-(1-2*x^2)*y/(4*x^6),y,x));
check_result(eqn, ans);

/* Kamke 2. 405  */ 
assume(notequal(a,9));
(pn_(405),ans:ode2singular(eqn:'diff(y,x,2)=(2*x^2+1)*'diff(y,x,1)/x^3-(a*x^4+10*x^2+1)*y/(4*x^6),y,x));
check_result(eqn, ans);
forget(notequal(a,9));

/* Kamke 2. 406  */
(pn_(406),ans:ode2singular(eqn:'diff(y,x,2)=-27*x*y/(16*(x^3-1)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 407  */ 
(pn_(407),ans:ode2singular(eqn:'diff(y,x,2)=(-b3*(-bl3-al3+1)/(b3*x-a3)-b2*(-bl2-al2+1)/(b2*x-a2)-b1*(-bl1-al1+1)/(b1*x-a1))*'diff(y,x,1)-(al3*(a3*b1-a1*b3)*(a2*b3-a3*b2)*bl3/(b3*x-a3)+al2*(a1*b2-a2*b1)*(a2*b3-a3*b2)*bl2/(b2*x-a2)+al1*(a1*b2-a2*b1)*(a3*b1-a1*b3)*bl1/(b1*x-a1))*y/((b1*x-a1)*(b2*x-a2)*(b3*x-a3)),y,x));

/* Kamke 2. 408  */ 
(pn_(408),ans:ode2singular(eqn:'diff(y,x,2)=((x^2-a1)*(x^2-a2)*(x^2-a3)-x^2*((x^2-a2)*(x^2-a3)+(x^2-a1)*(x^2-a3)+(x^2-a1)*(x^2-a2)))*'diff(y,x,1)/(x*(x^2-a1)*(x^2-a2)*(x^2-a3))-y*(B+x^2*A)/(x*(x^2-a1)*(x^2-a2)*(x^2-a3)),y,x));
check_result(eqn, ans);

/* Kamke 2. 409  */ 
assume(a>1);
(pn_(409),ans:ode2singular(eqn:'diff(y,x,2)=-a*'diff(y,x,1)/x-b^2*y/x^(2*a),y,x));
check_result(eqn, ans);
forget(a>1);

/* Kamke 2. 410  */ 
(pn_(410),ans:ode2singular(eqn:'diff(y,x,2)=(-a*p*x^b-q)*'diff(y,x,1)/(x*(a*x^b-1))-(a*r*x^b+s)*y/(x^2*(a*x^b-1)),y,x));
check_result(eqn, ans);

/* Kamke 2. 411  */ 
(pn_(411),ans:ode2singular(eqn:'diff(y,x,2)=y/(%e^x+1),y,x));
check_result(eqn, ans);

/* Kamke 2. 412  */ 
(pn_(412),ans:ode2singular(eqn:'diff(y,x,2)='diff(y,x,1)/(x*log(x))+log(x)^2*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 413  */ 
(pn_(413),ans:ode2singular(eqn:'diff(y,x,2)='diff(y,x,1)/(x*(log(x)-1))-y/(x^2*(log(x)-1)),y,x));
check_result(eqn, ans);

/* Kamke 2. 414  */ 
(pn_(414),ans:ode2singular(eqn:'diff(y,x,2)=(a^2*sinh(x)^2+(n-1)*n)*y/sinh(x)^2,y,x));
check_result(eqn, ans);

/* Kamke 2. 415  */ 
(pn_(415),ans:ode2singular(eqn:'diff(y,x,2)=-2*n*cosh(x)*'diff(y,x,1)/sinh(x)-(n^2-a^2)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 416  */ 
(pn_(416),ans:ode2singular(eqn:'diff(y,x,2)=(-2*n-1)*cos(x)*'diff(y,x,1)/sin(x)-(v-n)*(v+n+1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 417  */ 
(pn_(417),ans:ode2singular(eqn:'diff(y,x,2)=(cos(x)-sin(x)^2)*'diff(y,x,1)/sin(x)-sin(x)^2*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 418  */ 
(pn_(418),ans:ode2singular(eqn:'diff(y,x,2)=sin(x)*y/(x*cos(x)-sin(x))-x*sin(x)*'diff(y,x,1)/(x*cos(x)-sin(x)),y,x));
check_result(eqn, ans);

/* Kamke 2. 419  */ 
(pn_(419),ans:ode2singular(eqn:'diff(y,x,2)=(2*x*cos(x)-x^2*sin(x))*'diff(y,x,1)/(x^2*cos(x))-(2*x*cos(x)-x*sin(x))*y/(x^2*cos(x)),y,x));
check_result(eqn, ans);

/* Kamke 2. 420  */ 
(pn_(420),ans:ode2singular(eqn:cos(x)^2*'diff(y,x,2)-(a*cos(x)^2+(n-1)*n)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 421  */ 
(pn_(421),ans:ode2singular(eqn:'diff(y,x,2)=-a*(n-1)*sin(2*a*x)*'diff(y,x,1)/cos(a*x)^2-a^2*n*((n-1)*sin(a*x)^2+cos(a*x)^2)*y/cos(a*x)^2,y,x));
check_result(eqn, ans);

/* Kamke 2. 422  */ 
(pn_(422),ans:ode2singular(eqn:'diff(y,x,2)=2*y/sin(x)^2,y,x));
check_result(eqn, ans);

/* Kamke 2. 423  */ 
(pn_(423),ans:ode2singular(eqn:'diff(y,x,2)=-a*y/sin(x)^2,y,x));
check_result(eqn, ans);

testmode: false;
