(load("contrib_ode"),0);
0$
load(ode2singular);
/* ODE tests - Second order linear equations 1-50

  Reference:
    E Kamke, Differentialgleichungen Losungsmethoden und Losungen, 
    Vol 1, Geest & Portig, Leipzig, 1961
*/

/* Print ode number*/
(pn_(n_):=print("Kamke ODE 2.",n_),true);
true;


check_result(eqn, ans) := block(
    [],
    if length(ans)>0 then
        (
        ode_check(eqn,ans[1])
        )
    )$

testmode: true;

/* Kamke 2. 1  */ 
(pn_(1),ans:ode2singular(eqn:'diff(y,x,2),y,x));
check_result(eqn, ans);

/* Kamke 2. 2  */ 
(pn_(2),ans:ode2singular(eqn:'diff(y,x,2)+y,y,x));
check_result(eqn, ans);

/* Kamke 2. 3  */ 
(pn_(3),ans:ode2singular(eqn:'diff(y,x,2)+y-sin(n*x),y,x));
check_result(eqn, ans);


/* Kamke 2. 4  */ 
(pn_(4),ans:ode2singular(eqn:'diff(y,x,2)+y-a*cos(b*x),y,x));
check_result(eqn, ans);


/* Kamke 2. 5  */ 
(pn_(5),ans:ode2singular(eqn:'diff(y,x,2)+y-sin(a*x)*sin(b*x),y,x));
check_result(eqn, ans);


/* Kamke 2. 6  */ 
(pn_(6),ans:ode2singular(eqn:'diff(y,x,2)-y,y,x));
check_result(eqn, ans);


/* Kamke 2. 7  */ 
(pn_(7),ans:ode2singular(eqn:'diff(y,x,2)-2*y-4*x^2*%e^x^2,y,x));
check_result(eqn, ans);


/* Kamke 2. 8  CHECKME */ 
assume(a>0);
(pn_(8),ans:ode2singular(eqn:'diff(y,x,2)+a^2*y-cot(a*x),y,x));
check_result(eqn, ans);
forget(a>0);

/* Kamke 2. 9  */ 
assume(l>0);
(pn_(9),ans:ode2singular(eqn:'diff(y,x,2)+l*y,y,x));
check_result(eqn, ans);
forget(l>0);

/* Kamke 2. 10  */
(pn_(10),ans:ode2singular(eqn:'diff(y,x,2)+(a*x+b)*y,y,x));
check_result(eqn, ans);


/* Kamke 2. 11  */ 
(pn_(11),ans:ode2singular(eqn:'diff(y,x,2)-(x^2+1)*y,y,x));
check_result(eqn, ans);


/* Kamke 2. 12  */ 
(pn_(12),ans:ode2singular(eqn:'diff(y,x,2)-(x^2+a)*y,y,x));
check_result(eqn, ans);


/* Kamke 2. 13  */ 
(pn_(13),ans:ode2singular(eqn:'diff(y,x,2)-(a^2*x^2+a)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 14  */ 
(pn_(14),ans:ode2singular(eqn:'diff(y,x,2)-c*x^a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 15  */ 
(pn_(15),ans:ode2singular(eqn:'diff(y,x,2)-(a^2*x^(2*n)-1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 16  */ 
(pn_(16),ans:ode2singular(eqn:'diff(y,x,2)+(a*x^(2*c)+b*x^(c-1))*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 17  */ 
(pn_(17),ans:ode2singular(eqn:'diff(y,x,2)+(%e^(2*x)-v^2)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 18  */ 
(pn_(18),ans:ode2singular(eqn:'diff(y,x,2)+a*%e^(b*x)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 19  */ 
(pn_(19),ans:ode2singular(eqn:'diff(y,x,2)-(4*a^2*b^2*x^2*%e^(2*b*x^2)-1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 20  */ 
(pn_(20),ans:ode2singular(eqn:'diff(y,x,2)+(a*%e^(2*x)+b*%e^x+c)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 21  */ 
(pn_(21),ans:ode2singular(eqn:'diff(y,x,2)+(a*cos(x)^2+b)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 22  */ 
(pn_(22),ans:ode2singular(eqn:'diff(y,x,2)+(a*cos(2*x)+b)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 23  */ 
(pn_(23),ans:ode2singular(eqn:'diff(y,x,2)+(a*cos(x)^2+b)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 24  */ 
(pn_(24),ans:ode2singular(eqn:'diff(y,x,2)-(2*tan(x)^2+1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 25  */ 
(pn_(25),ans:ode2singular(eqn:'diff(y,x,2)-((n-1)*n/sin(x)^2+(m-1)*m/cos(x)^2+a)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 26  */ 
(pn_(26),ans:ode2singular(eqn:'diff(y,x,2)-y*(B+p(x)*A),y,x));
check_result(eqn, ans);

/* Kamke 2. 27  */ 
(pn_(27),ans:ode2singular(eqn:'diff(y,x,2)+(a*jacobi_sn(x,m)^2+b)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 28  */ 
(pn_(28),ans:ode2singular(eqn:'diff(y,x,2)-('diff(p(x),x,4)/30+7*'diff(p(x),x,2)/3+a*p(x)+b)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 29  */ 
(pn_(29),ans:ode2singular(eqn:'diff(y,x,2)-('diff(f(x),x,1)+f(x)^2)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 30  */ 
(pn_(30),ans:ode2singular(eqn:'diff(y,x,2)+(P(x)+l)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 31  */ 
(pn_(31),ans:ode2singular(eqn:'diff(y,x,2)-f(x)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 32  */ 
(pn_(32),ans:ode2singular(eqn:'diff(y,x,2)+('diff(g(x),x,3)/(2*'diff(g(x),x,1))-3*('diff(g(x),x,2))^2/(4*('diff(g(x),x,1))^2)+(1/4-v^2)*('diff(g(x),x,1))^2/g(x)+('diff(g(x),x,1))^2)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 33  */ 
(pn_(33),ans:ode2singular(eqn:'diff(y,x,2)+'diff(y,x,1)+a*%e^-(2*x)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 34  */ 
(pn_(34),ans:ode2singular(eqn:'diff(y,x,2)-'diff(y,x,1)+%e^(2*x)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 35  */ 
assume(a^2>4*b);
(pn_(35),ans:ode2singular(eqn:'diff(y,x,2)+a*'diff(y,x,1)+b*y,y,x));
check_result(eqn, ans);
forget(a^2>4*b);


/* Kamke 2. 36  */ 
assume(a^2>4*b);
(pn_(36),ans:ode2singular(eqn:'diff(y,x,2)+a*'diff(y,x,1)+b*y-f(x),y,x));
check_result(eqn, ans);
forget(a^2>4*b);


/* Kamke 2. 37  */ 
(pn_(37),ans:ode2singular(eqn:'diff(y,x,2)+a*'diff(y,x,1)+(-b^2*x^2-c)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 38  */ 
(pn_(38),ans:ode2singular(eqn:'diff(y,x,2)+2*a*'diff(y,x,1)+f(x)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 39  */ 
(pn_(39),ans:ode2singular(eqn:'diff(y,x,2)+x*'diff(y,x,1)+y,y,x));
check_result(eqn, ans);

/* Kamke 2. 40  */ 
(pn_(40),ans:ode2singular(eqn:'diff(y,x,2)+x*'diff(y,x,1)-y,y,x));
check_result(eqn, ans);

/* Kamke 2. 41  */ 
(pn_(41),ans:ode2singular(eqn:'diff(y,x,2)+x*'diff(y,x,1)+(n+1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 42  */ 
(pn_(42),ans:ode2singular(eqn:'diff(y,x,2)+x*'diff(y,x,1)-n*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 43  */ 
(pn_(43),ans:ode2singular(eqn:'diff(y,x,2)-x*'diff(y,x,1)+2*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 44  */ 
(pn_(44),ans:ode2singular(eqn:'diff(y,x,2)-x*'diff(y,x,1)-a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 45  */ 
(pn_(45),ans:ode2singular(eqn:'diff(y,x,2)-x*'diff(y,x,1)+(x-1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 46  */ 
(pn_(46),ans:ode2singular(eqn:'diff(y,x,2)-2*x*'diff(y,x,1)+a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 47  */ 
(pn_(47),ans:ode2singular(eqn:'diff(y,x,2)+4*x*'diff(y,x,1)+(4*x^2+2)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 48  */ 
(pn_(48),ans:ode2singular(eqn:'diff(y,x,2)-4*x*'diff(y,x,1)+(3*x^2+2*n-1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 49  */ 
(pn_(49),ans:ode2singular(eqn:'diff(y,x,2)-4*x*'diff(y,x,1)+(4*x^2-1)*y-%e^x,y,x));
check_result(eqn, ans);

/* Kamke 2. 50  */ 
(pn_(50),ans:ode2singular(eqn:'diff(y,x,2)-4*x*'diff(y,x,1)+(4*x^2-2)*y,y,x));
check_result(eqn, ans);

testmode: false;