(load("contrib_ode"),0);
0$

/* ODE tests - Second order linear equations 424-445

  Reference:
    E Kamke, Differentialgleichungen Losungsmethoden und Losungen, 
    Vol 1, Geest & Portig, Leipzig, 1961
*/

/* Print ode number*/
(pn_(n_):=print("Kamke ODE 2.",n_),true);
true;


check_result(eqn, ans) := block(
    [],
    if length(ans)>0 then
        (
        ode_check(eqn,ans[1])
        )
    )$

testmode: true;

/* Kamke 2. 424  */ 
(pn_(424),ans:ode2singular(eqn:sin(x)^2*'diff(y,x,2)-(a*sin(x)^2+(n-1)*n)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 425  */ 
(pn_(425),ans:ode2singular(eqn:'diff(y,x,2)=(a^2*cos(x)^2+(3-2*a)*cos(x)-3*a+3)*y/sin(x)^2,y,x));
check_result(eqn, ans);

/* Kamke 2. 426  */ 
(pn_(426),ans:ode2singular(eqn:sin(x)^2*'diff(y,x,2)-(a^2*cos(x)^2+b*cos(x)+b^2/(2*a-3)^2+3*a+2)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 427  */ 
(pn_(427),ans:ode2singular(eqn:'diff(y,x,2)=(a*(a+1)*b*sin(2*x)-((a+1)^2-a^2*b^2)*sin(x)^2+(a-1)*a)*y/sin(x)^2,y,x));
check_result(eqn, ans);

/* Kamke 2. 428  */ 
(pn_(428),ans:ode2singular(eqn:'diff(y,x,2)=(-b*sin(x)^2-a*cos(x)^2-c)*y/sin(x)^2,y,x));
check_result(eqn, ans);

/* Kamke 2. 429  */ 
(pn_(429),ans:ode2singular(eqn:'diff(y,x,2)=y/sin(x)^2-cos(x)*'diff(y,x,1)/sin(x),y,x));
check_result(eqn, ans);

/* Kamke 2. 430  */ 
(pn_(430),ans:ode2singular(eqn:'diff(y,x,2)=-cos(x)*'diff(y,x,1)/sin(x)-(v*(v+1)*sin(x)^2-n^2)*y/sin(x)^2,y,x));
check_result(eqn, ans);

/* Kamke 2. 431  */ 
(pn_(431),ans:ode2singular(eqn:'diff(y,x,2)=cos(2*x)*'diff(y,x,1)/sin(2*x)-2*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 432  */ 
(pn_(432),ans:ode2singular(eqn:'diff(y,x,2)=-cos(x)*'diff(y,x,1)/sin(x)-(-17*sin(x)^2-1)*y/(4*sin(x)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 433  */ 
(pn_(433),ans:ode2singular(eqn:'diff(y,x,2)=-sin(x)*'diff(y,x,1)/cos(x)-(x^2*sin(x)^2-24*cos(x)^2+2*x^2)*y/(4*x^2*cos(x)^2)+sqrt(cos(x)),y,x));
check_result(eqn, ans);

/* Kamke 2. 434  */ 
(pn_(434),ans:ode2singular(eqn:'diff(y,x,2)=-b*cos(x)*'diff(y,x,1)/(a*sin(x))-(c*cos(x)^2+d*cos(x)+e)*y/(a*sin(x)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 435  */ 
(pn_(435),ans:ode2singular(eqn:'diff(y,x,2)=-4*sin(3*x)*y/sin(x)^3,y,x));
check_result(eqn, ans);

/* Kamke 2. 436  */ 
(pn_(436),ans:ode2singular(eqn:'diff(y,x,2)=-(4*v*(v+1)*sin(x)^2-cos(x)^2-4*n^2+2)*y/(4*sin(x)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 437  */ 
(pn_(437),ans:ode2singular(eqn:'diff(y,x,2)=(3*sin(x)^2+1)*'diff(y,x,1)/(cos(x)*sin(x))+sin(x)^2*y/cos(x)^2,y,x));
check_result(eqn, ans);

/* Kamke 2. 438  */ 
(pn_(438),ans:ode2singular(eqn:'diff(y,x,2)=(a*cos(x)^2*sin(x)^2+(m-1)*m*sin(x)^2+(n-1)*n*cos(x)^2)*y/(cos(x)^2*sin(x)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 439  */ 
/*(pn_(439),ans:ode2singular(eqn:ode[439],y,x));*/
/*check_result(eqn, ans);*/

/* Kamke 2. 440  */ 
(pn_(440),ans:ode2singular(eqn:'diff(y,x,2)=('diff(phi(x),x,2)+phi(x)*'diff(phi(x),x,1)-phi(x^3))*'diff(y,x,1)/('diff(phi(x),x,1)+phi(x)^2)-(-phi(x)*'diff(phi(x),x,2)+('diff(phi(x),x,1))^2-phi(x)^2*'diff(phi(x),x,1))*y/('diff(phi(x),x,1)+phi(x)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 441  */ 
(pn_(441),ans:ode2singular(eqn:'diff(y,x,2)=(2*jacobi_sn(x,m)+jacobi_cn(x,m)*jacobi_dn(x,m))*'diff(y,x,1)/(jacobi_sn(x,m)^2-jacobi_sn(a,m)^2)-(-4*jacobi_sn(a,m)^2*(m+1)+6*jacobi_sn(a,m)^4*m+2)*y/(jacobi_sn(x,m)^2-jacobi_sn(a,m)^2)-1/(jacobi_sn(x,m)^2-jacobi_sn(a,m)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 442  */ 
(pn_(442),ans:ode2singular(eqn:'diff(y,x,2)=y/f(x)-x*'diff(y,x,1)/f(x),y,x));
check_result(eqn, ans);

/* Kamke 2. 443  */ 
(pn_(443),ans:ode2singular(eqn:'diff(y,x,2)=-'diff(f(x),x,1)*'diff(y,x,1)/(2*f(x))-g(x)*y/f(x),y,x));
check_result(eqn, ans);

/* Kamke 2. 444  */ 
(pn_(444),ans:ode2singular(eqn:'diff(y,x,2)=-a*'diff(f(x),x,1)*'diff(y,x,1)/f(x)-b*f(x)^(2*a)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 445  */ 
(pn_(445),ans:ode2singular(eqn:'diff(y,x,2)=((g(x)^2-1)*(f(x)*'diff(g(x),x,2)+2*'diff(f(x),x,1)*'diff(g(x),x,1))-2*f(x)*g(x)*('diff(g(x),x,1))^2)*'diff(y,x,1)/(f(x)*(g(x)^2-1)*'diff(g(x),x,1))-((g(x)^2-1)*('diff(f(x),x,1)*(f(x)*'diff(g(x),x,2)+2*'diff(f(x),x,1)*'diff(g(x),x,1))-f(x)*'diff(f(x),x,2)*'diff(g(x),x,1))-f(x)*('diff(g(x),x,1))^2*(v*(v+1)*f(x)*'diff(g(x),x,1)+2*g(x)*'diff(f(x),x,1)))*y/(f(x)^2*(g(x)^2-1)*'diff(g(x),x,1)),y,x));
check_result(eqn, ans);

testmode: false;