(load("contrib_ode"),0);
0$
load(ode2singular);
/* ODE tests - Second order linear equations 101-150

  Reference:
    E Kamke, Differentialgleichungen Losungsmethoden und Losungen, 
    Vol 1, Geest & Portig, Leipzig, 1961
*/

/* Print ode number*/
(pn_(n_):=print("Kamke ODE 2.",n_),true);
true;


check_result(eqn, ans) := block(
    [],
    if length(ans)>0 then
        (
        ode_check(eqn,ans[1])
        )
    )$

testmode: true;

/* Kamke 2. 101  */ 
(pn_(101),ans:ode2singular(eqn:x*'diff(y,x,2)+2*'diff(y,x,1)+a*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 102  */
(pn_(102),ans:ode2singular(eqn:x*'diff(y,x,2)+2*'diff(y,x,1)+a*x^2*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 103  */ 
(pn_(103),ans:ode2singular(eqn:x*'diff(y,x,2)-2*'diff(y,x,1)+a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 104  */ 
(pn_(104),ans:ode2singular(eqn:x*'diff(y,x,2)+v*'diff(y,x,1)+a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 105  */ 
(pn_(105),ans:ode2singular(eqn:x*'diff(y,x,2)+a*'diff(y,x,1)+b*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 106  */ 
(pn_(106),ans:ode2singular(eqn:x*'diff(y,x,2)+a*'diff(y,x,1)+b*x^a1*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 107  */ 
(pn_(107),ans:ode2singular(eqn:x*'diff(y,x,2)+(x+b)*'diff(y,x,1)+a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 108  */ 
(pn_(108),ans:ode2singular(eqn:x*'diff(y,x,2)+(x+b+a)*'diff(y,x,1)+a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 109  */ 
(pn_(109),ans:ode2singular(eqn:x*'diff(y,x,2)-x*'diff(y,x,1)-y-x*(x+1)*%e^x,y,x));
check_result(eqn, ans);

/* Kamke 2. 110 */ 
assume(x>0,x+4*a>0);
(pn_(110),ans:ode2singular(eqn:x*'diff(y,x,2)-x*'diff(y,x,1)-a*y,y,x));
check_result(eqn, ans);
forget(x>0,x+4*a>0);

/* Kamke 2. 111 */ 
(pn_(111),ans:ode2singular(eqn:x*'diff(y,x,2)-(x+1)*'diff(y,x,1)+y,y,x));
check_result(eqn, ans);

/* Kamke 2. 112  */ 
(pn_(112),ans:ode2singular(eqn:x*'diff(y,x,2)-(x+1)*'diff(y,x,1)-2*(x-1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 113  */ 
assume(x^2+(4*a-2*b)*x+b^2>0);
[x^2+(4*a-2*b)*x+b^2>0];
(pn_(113),ans:ode2singular(eqn:x*'diff(y,x,2)+(b-x)*'diff(y,x,1)-a*y,y,x));
check_result(eqn, ans);
forget(x^2+(4*a-2*b)*x+b^2>0);

/* Kamke 2. 114  */ 
(pn_(114),ans:ode2singular(eqn:x*'diff(y,x,2)-2*(x-1)*'diff(y,x,1)-y,y,x));
check_result(eqn, ans);

/* Kamke 2. 115  */ 
(pn_(115),ans:ode2singular(eqn:x*'diff(y,x,2)-(3*x-2)*'diff(y,x,1)+(3-2*x)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 116  */ 
(pn_(116),ans:ode2singular(eqn:x*'diff(y,x,2)+(a*x+n+b)*'diff(y,x,1)+a*n*y,y,x));[y = %k2*kummer_u(n,n+b,-a*x)+%k1*kummer_m(n,n+b,-a*x)];
check_result(eqn, ans);

/* Kamke 2. 117  */ 
(pn_(117),ans:ode2singular(eqn:x*'diff(y,x,2)-(b+a)*(x+1)*'diff(y,x,1)+a*b*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 118  */ 
(pn_(118),ans:ode2singular(eqn:x*'diff(y,x,2)+((b+a)*x+n+m)*'diff(y,x,1)+(a*b*x+a*n+b*m)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 119  */
/* This causes 2.160 to fail for no obvious reason.  Result is OK */

assume(notequal(b,-1/2));
[notequal(b,-1/2)];
(pn_(119),ans:ode2singular(eqn:x*'diff(y,x,2)-2*(a*x+b)*'diff(y,x,1)+(a^2*x+2*a*b)*y,y,x));
check_result(eqn, ans);
forget(notequal(b,-1/2));


/* Kamke 2. 120  */ 
(pn_(120),ans:ode2singular(eqn:x*'diff(y,x,2)+(a*x+b)*'diff(y,x,1)+(c*x+d)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 121  */ 
(pn_(121),ans:ode2singular(eqn:x*'diff(y,x,2)-(x^2-x)*'diff(y,x,1)+(x-1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 122  */ 
(pn_(122),ans:ode2singular(eqn:x*'diff(y,x,2)-(x^2-x-2)*'diff(y,x,1)-x*(x+3)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 123  */ 
assume(b>0,b>a^2);
(pn_(123),ans:ode2singular(eqn:x*'diff(y,x,2)-(2*a*x^2+1)*'diff(y,x,1)+b*x^3*y,y,x));
check_result(eqn, ans);
forget(b>0,b>a^2);

/* Kamke 2. 124  */ 
(pn_(124),ans:ode2singular(eqn:x*'diff(y,x,2)-2*(x^2-a)*'diff(y,x,1)+2*n*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 125  */ 
(pn_(125),ans:ode2singular(eqn:x*'diff(y,x,2)+(4*x^2-1)*'diff(y,x,1)-4*x^3*y-4*x^5,y,x));
check_result(eqn, ans);

/* Kamke 2. 126  */ 
(pn_(126),ans:ode2singular(eqn:x*'diff(y,x,2)+(2*a*x^3-1)*'diff(y,x,1)+(a^2*x^3+a)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 127  */ 
(pn_(127),ans:ode2singular(eqn:x*'diff(y,x,2)+(2*a*x*log(x)+1)*'diff(y,x,1)+(a^2*x*log(x)^2+a*log(x)+a)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 128  */ 
(pn_(128),ans:ode2singular(eqn:x*'diff(y,x,2)+(x*f(x)+2)*'diff(y,x,1)+f(x)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 129  */ 
(pn_(129),ans:ode2singular(eqn:(x-3)*'diff(y,x,2)-(4*x-9)*'diff(y,x,1)+(3*x-6)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 130  */ 
(pn_(130),ans:ode2singular(eqn:2*x*'diff(y,x,2)+'diff(y,x,1)+a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 131  */ 
(pn_(131),ans:ode2singular(eqn:2*x*'diff(y,x,2)-(x-1)*'diff(y,x,1)+a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 132  */ 
assume(4*x^2+(-8*a-4)*x+1>0);
(pn_(132),ans:ode2singular(eqn:2*x*'diff(y,x,2)-(2*x-1)*'diff(y,x,1)+a*y,y,x));
check_result(eqn, ans);
forget(4*x^2+(-8*a-4)*x+1>0);

/* Kamke 2. 133  */ 
(pn_(133),ans:ode2singular(eqn:(2*x-1)*'diff(y,x,2)-(3*x-4)*'diff(y,x,1)+(x-3)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 134  */ 
(pn_(134),ans:ode2singular(eqn:4*x*'diff(y,x,2)-(x+a)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 135  */ 
(pn_(135),ans:ode2singular(eqn:4*x*'diff(y,x,2)+2*'diff(y,x,1)-y,y,x));
check_result(eqn, ans);

/* Kamke 2. 136  */ 
(pn_(136),ans:ode2singular(eqn:4*x*'diff(y,x,2)+4*'diff(y,x,1)+(-x-2)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 137  */ 
(pn_(137),ans:ode2singular(eqn:4*x*'diff(y,x,2)+(-x-2)*y+L*y+4*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 138  */ 
(pn_(138),ans:ode2singular(eqn:4*x*'diff(y,x,2)+4*m*'diff(y,x,1)+(-x+4*n+2*m)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 139  */ 
(pn_(139),ans:ode2singular(eqn:16*x*'diff(y,x,2)+8*'diff(y,x,1)+(-x-a)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 140  */ 
(pn_(140),ans:ode2singular(eqn:a*x*'diff(y,x,2)+b*'diff(y,x,1)+c*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 141  */ 
(pn_(141),ans:ode2singular(eqn:a*x*'diff(y,x,2)+(b*x+3*a)*'diff(y,x,1)+3*b*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 142  */ 
(pn_(142),ans:ode2singular(eqn:5*(a*x+b)*'diff(y,x,2)+8*a*'diff(y,x,1)+c*(a*x+b)^(1/5)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 143  */ 
(pn_(143),ans:ode2singular(eqn:2*a*x*'diff(y,x,2)+(b*x+a)*'diff(y,x,1)+c*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 144  */ 
(pn_(144),ans:ode2singular(eqn:2*a*x*'diff(y,x,2)+(b*x+3*a)*'diff(y,x,1)+c*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 145  */
(pn_(145),ans:ode2singular(eqn:(a2*x+b2)*'diff(y,x,2)+(a1*x+b1)*'diff(y,x,1)+(a0*x+b0)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 146  */ 
assume(x>0);
(pn_(146),ans:ode2singular(eqn:x^2*'diff(y,x,2)-6*y,y,x));
check_result(eqn, ans);
forget(x>0);

/* Kamke 2. 147  */ 
assume(x>0);
(pn_(147),ans:ode2singular(eqn:x^2*'diff(y,x,2)-12*y,y,x));
check_result(eqn, ans);
forget(x>0);

/* Kamke 2. 148  */ 
assume(a>0,a>1/4);
[a>0,a>1/4];
(pn_(148),ans:ode2singular(eqn:x^2*'diff(y,x,2)+a*y,y,x));
check_result(eqn, ans);
forget(a>0,a>1/4);

/* Kamke 2. 149  */ 
(pn_(149),ans:ode2singular(eqn:x^2*'diff(y,x,2)+(a*x+b)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 150  */ 
(pn_(150),ans:ode2singular(eqn:x^2*'diff(y,x,2)+(x^2-2)*y,y,x));
check_result(eqn, ans);

testmode: false;