(load("contrib_ode"),0);
0$

/* ODE tests - Second order linear equations 301-350

  Reference:
    E Kamke, Differentialgleichungen Losungsmethoden und Losungen, 
    Vol 1, Geest & Portig, Leipzig, 1961
*/

/* Print ode number*/
(pn_(n_):=print("Kamke ODE 2.",n_),true);
true;


check_result(eqn, ans) := block(
    [],
    if length(ans)>0 then
        (
        ode_check(eqn,ans[1])
        )
    )$

testmode: true;

/* Kamke 2. 301  */ 
(pn_(301),ans:ode2singular(eqn:(a*x^2+b*x)*'diff(y,x,2)+2*b*'diff(y,x,1)-2*a*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 302  */ 
(pn_(302),ans:ode2singular(eqn:(a*x+b)^2*'diff(y,x,2)*A2+(a*x+b)*'diff(y,x,1)*A1+(a*x+b)*y*A0,y,x),0);
check_result(eqn, ans);

/* Kamke 2. 303  */ 
assume(4*a*c-b^2>0);
(pn_(303),ans:ode2singular(eqn:(a*x^2+b*x+c)*'diff(y,x,2)+(d*x+f)*'diff(y,x,1)+g*y,y,x));
check_result(eqn, ans);
forget(4*a*c-b^2>0);

/* Kamke 2. 304  */ 
(pn_(304),ans:ode2singular(eqn:x^3*'diff(y,x,2)+x*'diff(y,x,1)+(-2*x-3)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 305  */ 
(pn_(305),ans:ode2singular(eqn:x^3*'diff(y,x,2)+2*x*'diff(y,x,1)-y,y,x));
check_result(eqn, ans);

/* Kamke 2. 306  */ 
(pn_(306),ans:ode2singular(eqn:x^3*'diff(y,x,2)+x^2*'diff(y,x,1)+(a*x^2+b*x+a)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 307  */ 
(pn_(307),ans:ode2singular(eqn:x^3*'diff(y,x,2)+x*(x+1)*'diff(y,x,1)-2*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 308  */ 
(pn_(308),ans:ode2singular(eqn:x^3*'diff(y,x,2)-x^2*'diff(y,x,1)+x*y-log(x)^3,y,x));
check_result(eqn, ans);

/* Kamke 2. 309  */ 
(pn_(309),ans:ode2singular(eqn:x^3*'diff(y,x,2)-(x^2-1)*'diff(y,x,1)+x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 310  */ 
(pn_(310),ans:ode2singular(eqn:x^3*'diff(y,x,2)+3*x^2*'diff(y,x,1)+x*y-1,y,x));
check_result(eqn, ans);

/* Kamke 2. 311  */ 
(pn_(311),ans:ode2singular(eqn:x*(x^2+1)*'diff(y,x,2)+(2*x^2+1)*'diff(y,x,1)-v*(v+1)*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 312  */ 
(pn_(312),ans:ode2singular(eqn:x*(x^2+1)*'diff(y,x,2)+2*(x^2-1)*'diff(y,x,1)-2*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 313  */ 
(pn_(313),ans:ode2singular(eqn:x*(x^2+1)*'diff(y,x,2)+(2*(n+1)*x^2+2*n+1)*'diff(y,x,1)+(n-v)*(v+n+1)*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 314  */
(pn_(314),ans:ode2singular(eqn:x*(x^2+1)*'diff(y,x,2)-(2*(n-1)*x^2+2*n-1)*'diff(y,x,1)+(-v+n-1)*(v+n)*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 315 */ 
(pn_(315),ans:ode2singular(eqn:x*(x^2-1)*'diff(y,x,2)+'diff(y,x,1)+a*x^3*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 316  */
(pn_(316),ans:ode2singular(eqn:x*(x^2-1)*'diff(y,x,2)+(x^2-1)*'diff(y,x,1)-x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 317  */
(pn_(317),ans:ode2singular(eqn:x*(x^2-1)*'diff(y,x,2)+(3*x^2-1)*'diff(y,x,1)+x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 318  */
(pn_(318),ans:ode2singular(eqn:x*(x^2-1)*'diff(y,x,2)+(a*x^2+b)*'diff(y,x,1)+c*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 319 */ 
(pn_(319),ans:ode2singular(eqn:x*(x^2+2)*'diff(y,x,2)-'diff(y,x,1)-6*x*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 320  */ 
(pn_(320),ans:ode2singular(eqn:x*(x^2-2)*'diff(y,x,2)-(x^3+3*x^2-2*x-2)*'diff(y,x,1)+(x^2+4*x+2)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 321  */ 
(pn_(321),ans:ode2singular(eqn:x^2*(x+1)*'diff(y,x,2)-x*(2*x+1)*'diff(y,x,1)+(2*x+1)*y,y,x));
check_result(eqn, ans);

/* Kamke 2. 322  */ 
(pn_(322),ans:ode2singular(eqn:x^2*(x+1)*'diff(y,x,2)+2*x*(3*x+2)*'diff(y,x,1),y,x));
check_result(eqn, ans);

/* Kamke 2. 323  */ 
(pn_(323),ans:ode2singular(eqn:'diff(y,x,2)=2*(x+1)*y/((x-1)*x)-2*(x-2)*'diff(y,x,1)/((x-1)*x),y,x));
check_result(eqn, ans);

/* Kamke 2. 324  */ 
(pn_(324),ans:ode2singular(eqn:'diff(y,x,2)=(5*x-4)*'diff(y,x,1)/((x-1)*x)-(9*x-6)*y/((x-1)*x^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 325  */ 
(pn_(325),ans:ode2singular(eqn:'diff(y,x,2)=(-(b+a+1)*x-beta-alpha+1)*'diff(y,x,1)/((x-1)*x)-(a*b*x-alpha*beta)*y/((x-1)*x^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 326  */ 
(pn_(326),ans:ode2singular(eqn:'diff(y,x,2)=-'diff(y,x,1)/(x+1)-y/(x*(x+1)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 327  */ 
(pn_(327),ans:ode2singular(eqn:'diff(y,x,2)=2*'diff(y,x,1)/((x-2)*x)-y/((x-2)*x^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 328  */ 
(pn_(328),ans:ode2singular(eqn:'diff(y,x,2)=2*y/((x-1)^2*x),y,x));
check_result(eqn, ans);

/* Kamke 2. 329  */ 
(pn_(329),ans:ode2singular(eqn:'diff(y,x,2)=(-(beta+alpha+1)*x^2+(a*(gamma1+delta)-delta+beta+alpha+1)*x-a*gamma1)*'diff(y,x,1)/((x-1)*x*(x-a))-(alpha*beta*x-q)*y/((x-1)*x*(x-a)),y,x));
check_result(eqn, ans);

/* Kamke 2. 330  */ 
(pn_(330),ans:ode2singular(eqn:'diff(y,x,2)='diff(y,x,1)*(-C-x*B-x^2*A)/((x-a)*(x-b)*(x-c))-y*(E+x*D)/((x-a)*(x-b)*(x-c)),y,x));
check_result(eqn, ans);

/* Kamke 2. 331  */ 
(pn_(331),ans:ode2singular(eqn:'diff(y,x,2)=(x-4)*'diff(y,x,1)/(2*(x-2)*x)-(x-3)*y/(2*(x-2)*x^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 332  */ 
(pn_(332),ans:ode2singular(eqn:'diff(y,x,2)='diff(y,x,1)/(x+1)-(3*x+1)*y/(4*x^2*(x+1)),y,x));
check_result(eqn, ans);

/* Kamke 2. 333  */ 
(pn_(333),ans:ode2singular(eqn:'diff(y,x,2)=v*(v+1)*y/(4*x^2)-(3*x-1)*'diff(y,x,1)/(2*(x-1)*x),y,x));
check_result(eqn, ans);

/* Kamke 2. 334  */ 
(pn_(334),ans:ode2singular(eqn:'diff(y,x,2)=(1-(a+1)*x)*'diff(y,x,1)/((x-1)*x)-((a^2-b^2)*x+c^2)*y/(4*(x-1)*x^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 335  */ 
(pn_(335),ans:ode2singular(eqn:'diff(y,x,2)=-(3*x-1)*'diff(y,x,1)/(2*(x-1)*x)-(a*x+b)*y/(4*(x-1)^2*x),y,x));
check_result(eqn, ans);

/* Kamke 2. 336  */ 
(pn_(336),ans:ode2singular(eqn:'diff(y,x,2)=(3*x-1)*y/((x-1)*(2*x-1)^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 337  */
assume(a>b);
(pn_(337),ans:ode2singular(eqn:'diff(y,x,2)=-(3*x+2*b+a)*'diff(y,x,1)/(2*(x+a)*(x+b))-(a-b)*y/(4*(x+a)^2*(x+b)),y,x));
check_result(eqn, ans);
forget(a>b);

/* Kamke 2. 338  */ 
(pn_(338),ans:ode2singular(eqn:'diff(y,x,2)=(6*x-1)*'diff(y,x,1)/(3*(x-2)*x)+y/(3*(x-2)*x^2),y,x));
check_result(eqn, ans);

/* Kamke 2. 339  */ 
(pn_(339),ans:ode2singular(eqn:'diff(y,x,2)=(-a*(b+2)*x^2-(-d+c+1)*x)*'diff(y,x,1)/(x^2*(a*x+1))-(a*b*x-c*d)*y/(x^2*(a*x+1)),y,x));
check_result(eqn, ans);

/* Kamke 2. 340  */ 
(pn_(340),ans:ode2singular(eqn:'diff(y,x,2)=2*(a*x+2*b)*'diff(y,x,1)/(x*(a*x+b))-(2*a*x+6*b)*y/(x^2*(a*x+b)),y,x));
check_result(eqn, ans);

/* Kamke 2. 341  */ 
(pn_(341),ans:ode2singular(eqn:'diff(y,x,2)=x*A-(2*a*x+b)*'diff(y,x,1)/(x*(a*x+b))-(a*v*x-b)*y/(x^2*(a*x+b)),y,x));
check_result(eqn, ans);

/* Kamke 2. 342  */ 
(pn_(342),ans:ode2singular(eqn:'diff(y,x,2)=-a*y/x^4,y,x));
check_result(eqn, ans);

/* Kamke 2. 343  */ 
(pn_(343),ans:ode2singular(eqn:'diff(y,x,2)=(b*(x+b)-(1-a)*a*x^2)*y/x^4,y,x));
check_result(eqn, ans);

/* Kamke 2. 344  */ 
(pn_(344),ans:ode2singular(eqn:'diff(y,x,2)=(v^2-%e^(2/x))*y/x^4,y,x));
check_result(eqn, ans);

/* Kamke 2. 345  */ 
(pn_(345),ans:ode2singular(eqn:'diff(y,x,2)=2*y/x^4-'diff(y,x,1)/x^3,y,x));
check_result(eqn, ans);

/* Kamke 2. 346  */ 
(pn_(346),ans:ode2singular(eqn:'diff(y,x,2)=(b+a)*'diff(y,x,1)/x^2-((b+a)*x+a*b)*y/x^4,y,x));
check_result(eqn, ans);

/* Kamke 2. 347  */ 
(pn_(347),ans:ode2singular(eqn:'diff(y,x,2)=-'diff(y,x,1)/x-y/x^4,y,x));
check_result(eqn, ans);

/* Kamke 2. 348  */ 
(pn_(348),ans:ode2singular(eqn:'diff(y,x,2)=-'diff(y,x,1)/x-(a*(x^4+1)+b*x^2)*y/x^4,y,x));
check_result(eqn, ans);

/* Kamke 2. 349  */ 
(pn_(349),ans:ode2singular(eqn:'diff(y,x,2)=(-x^2-1)*'diff(y,x,1)/x^3-y/x^4,y,x));
check_result(eqn, ans);

/* Kamke 2. 350  */ 
(pn_(350),ans:ode2singular(eqn:'diff(y,x,2)=-2*'diff(y,x,1)/x-a^2*y/x^4,y,x));
check_result(eqn, ans);

testmode: false;